<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="apple-touch-icon" href="{{asset( config("settings.site_favicon")) }}"/>

    @yield("seo-tags")

    <title>{{ config("settings.site_". app()->getLocale() . "_title") }} @yield("page-title")</title>

    <!--== Favicon ==-->
    <link rel="shortcut icon" href="{{asset( config("settings.site_favicon")) }}" type="image/x-icon"/>
    <!--== styles ==-->
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
            crossorigin="anonymous"
    />
    <link href="{{ asset("assets/website/css/css/fontawesome5-all.css") }}" rel="stylesheet" type="text/css">
    <link href="{{ asset("assets/website/css/magnific-popup.css") }}" rel="stylesheet" type="text/css">
    <link href="{{ asset("assets/website/css/aos.css") }}" rel="stylesheet" type="text/css">
    <link href="{{ asset("assets/website/css/owl.carousel.css") }}" rel="stylesheet" type="text/css">

    @if(app()->getLocale() == "ar")
        <link href="{{ asset("assets/website/css/layout-ar.css") }}" rel="stylesheet" type="text/css">
    @else

        <link href="{{ asset("assets/website/css/layout-ar.css") }}" rel="stylesheet" type="text/css">

        @endif

    @stack("styles")

<!--[if lt IE 9]>
        <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        @include('website.partials.facebook-pixel')
</head>

<body>

<!-- Loader -->

{{--<div class="loading" delay-hide="1000"></div>--}}
<!-- Loader -->

<!--== Start Header Area Wrapper ==-->
@include("website.partials.header")
<!--== End Header Area Wrapper ==-->

<!-- Start Page Header Area -->
@yield("page-header-area")
<!-- End Page Header Area -->

<!--== Start Page Content Area Wrapper ==-->
@yield("content")
<!--== End Page Content Area Wrapper ==-->


<!--== Start Footer Area Wrapper ==-->
@include("website.partials.footer")
<!--== End Footer Area Wrapper ==-->

<!-- Back to top -->
<a href="#" onclick="topFunction()" id="back-to-top" class="btn btn-icon btn-primary back-to-top"><i
            data-feather="arrow-up" class="icons"></i></a>
<!-- Back to top -->

<!--=======================Javascript============================-->

<script src="{{ asset("assets/website/js/jquery-3.3.1.min.js") }}"></script>
<script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
<script src="{{ asset("assets/website/js/owl.carousel.js") }}"></script>
<script src="{{ asset("assets/website/js/jquery.magnific-popup.min.js") }}"></script>
<script src="{{ asset("assets/website/js/aos.js") }}"></script>

<script src="{{ asset("assets/website/js/custom.js") }}"></script>
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "سوفتيرا",
  "image" : "https://soft-era.net/images/logo.png",
  "telephone" : "00905343869441",
  "email" : "info@soft-era.net",
  "address" : {
    "@type" : "PostalAddress",
    "streetAddress" : "Cumhuriyet, Nazım Hikmet Bulvarı No:89, Beylikdüzü Osb",
    "addressLocality" : "Esenyurt",
    "addressRegion" : "İstanbul",
    "addressCountry" : "Turkey"
  }
}


</script>
@stack("scripts")
@include('website.partials.google-analytics')

</body>
</html>

